name: Build APK sur GitHub Actions

on:
  push:
    branches: [ main, 'fix/**' ]
  workflow_dispatch:

jobs:
  build-android-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configuration de Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache des dépendances NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installation des dépendances NPM
        run: npm ci

      - name: Génération et Compilation de l'APK (Expo CLI)
        env:
          CI: true
        run: npx expo run:android --variant debug

      - name: Sauvegarder l'APK généré comme artefact GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
